# Generated by Django 5.0 on 2026-02-13 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('meter_size', models.CharField(choices=[('DN15', 'DN15'), ('DN20', 'DN20'), ('DN25', 'DN25')], max_length=10)),
                ('meter_class', models.CharField(choices=[('R80', 'R80'), ('R100', 'R100'), ('R160', 'R160'), ('R200', 'R200'), ('R315', 'R315')], default='R160', max_length=10)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('meter_type', models.CharField(choices=[('mechanical', 'Mechanical'), ('ultrasonic', 'Ultrasonic'), ('electromagnetic', 'Electromagnetic')], max_length=30)),
                ('dut_mode', models.CharField(choices=[('rs485', 'RS485 Modbus'), ('manual', 'Manual Entry')], default='manual', max_length=10)),
                ('modbus_address', models.IntegerField(default=20)),
                ('modbus_baud', models.IntegerField(default=9600)),
                ('register_totalizer', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
