# Generated by Django 5.0 on 2026-02-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmeter',
            name='meter_class',
            field=models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('R80', 'R80'), ('R100', 'R100'), ('R160', 'R160'), ('R200', 'R200'), ('R315', 'R315')], default='B', max_length=10),
        ),
    ]
