# Generated by Django 5.0 on 2026-02-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('auto_lock_timeout', models.PositiveIntegerField(default=300, help_text='Auto-lock timeout in seconds (0 = disabled)')),
                ('buzzer_enabled', models.BooleanField(default=True)),
                ('datetime_format', models.CharField(choices=[('24h', '24-hour (14:30:00)'), ('12h', '12-hour (2:30 PM)')], default='24h', max_length=10)),
                ('display_brightness', models.PositiveIntegerField(default=100, help_text='Display brightness 0-100 (placeholder for HW integration)')),
                ('bench_id', models.CharField(blank=True, default='IIITB-BENCH-001', max_length=50)),
                ('software_version', models.CharField(default='1.0.0', editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Bench Settings',
                'verbose_name_plural': 'Bench Settings',
            },
        ),
    ]
