# Generated by Django 5.0 on 2026-02-15 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bench_ui', '0001_initial'),
        ('testing', '0003_alter_iso4064standard_meter_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DUTManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_point', models.CharField(max_length=5)),
                ('before_value_l', models.FloatField()),
                ('before_entered_at', models.DateTimeField()),
                ('after_value_l', models.FloatField(blank=True, null=True)),
                ('after_entered_at', models.DateTimeField(blank=True, null=True)),
                ('volume_l', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('before_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='testing.test')),
            ],
            options={
                'verbose_name': 'DUT Manual Entry',
                'verbose_name_plural': 'DUT Manual Entries',
                'ordering': ['q_point'],
                'unique_together': {('test', 'q_point')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('q_point', models.CharField(blank=True, max_length=5)),
                ('trigger', models.CharField(choices=[('periodic', 'Periodic'), ('event', 'Event')], default='periodic', max_length=10)),
                ('event_label', models.CharField(blank=True, max_length=50)),
                ('flow_rate_lph', models.FloatField(default=0.0)),
                ('em_totalizer_l', models.FloatField(default=0.0)),
                ('weight_kg', models.FloatField(default=0.0)),
                ('pressure_upstream_bar', models.FloatField(default=0.0)),
                ('pressure_downstream_bar', models.FloatField(default=0.0)),
                ('water_temp_c', models.FloatField(default=0.0)),
                ('vfd_freq_hz', models.FloatField(default=0.0)),
                ('vfd_current_a', models.FloatField(default=0.0)),
                ('dut_totalizer_l', models.FloatField(blank=True, null=True)),
                ('diverter', models.CharField(default='BYPASS', max_length=10)),
                ('active_lane', models.CharField(blank=True, max_length=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='testing.test')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['test', 'timestamp'], name='bench_ui_se_test_id_2417b9_idx'), models.Index(fields=['test', 'q_point'], name='bench_ui_se_test_id_de9217_idx')],
            },
        ),
    ]
