# Generated by Django 5.0 on 2026-02-13 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISO4064Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_size', models.CharField(max_length=10)),
                ('meter_class', models.CharField(max_length=10)),
                ('q_point', models.CharField(max_length=5)),
                ('flow_rate_lph', models.FloatField()),
                ('test_volume_l', models.FloatField()),
                ('duration_s', models.IntegerField()),
                ('mpe_pct', models.FloatField()),
                ('zone', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['meter_size', 'meter_class', 'q_point'],
                'unique_together': {('meter_size', 'meter_class', 'q_point')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='pending', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_comment', models.TextField(blank=True)),
                ('overall_pass', models.BooleanField(null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('certificate_pdf', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('bench', 'Bench'), ('lab', 'Lab')], default='bench', max_length=10)),
                ('current_q_point', models.CharField(blank=True, max_length=5)),
                ('current_state', models.CharField(blank=True, max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tests', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_tests', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.testmeter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_point', models.CharField(max_length=5)),
                ('target_flow_lph', models.FloatField()),
                ('actual_flow_lph', models.FloatField(blank=True, null=True)),
                ('ref_volume_l', models.FloatField(blank=True, null=True)),
                ('dut_volume_l', models.FloatField(blank=True, null=True)),
                ('error_pct', models.FloatField(blank=True, null=True)),
                ('mpe_pct', models.FloatField()),
                ('passed', models.BooleanField(null=True)),
                ('pressure_up_bar', models.FloatField(blank=True, null=True)),
                ('pressure_dn_bar', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('duration_s', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testing.test')),
            ],
            options={
                'ordering': ['q_point'],
                'unique_together': {('test', 'q_point')},
            },
        ),
    ]
