# Generated by Django 5.0 on 2026-02-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_test_test_class_alter_iso4064standard_meter_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso4064standard',
            name='meter_class',
            field=models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('R80', 'R80'), ('R100', 'R100'), ('R160', 'R160'), ('R200', 'R200')], max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_class',
            field=models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('R80', 'R80'), ('R100', 'R100'), ('R160', 'R160'), ('R200', 'R200')], default='B', help_text='Metrological class this test was run against', max_length=10),
        ),
    ]
