# Generated by Django 5.0 on 2026-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('manager', 'Manager'), ('bench_tech', 'Bench Technician'), ('lab_tech', 'Lab Technician')], default='lab_tech', max_length=20),
        ),
    ]
