# Generated by Django 5.0 on 2026-02-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#4CAF50', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('valve', 'Valve'), ('sensor_pressure', 'Pressure Sensor'), ('sensor_temperature', 'Temperature Sensor'), ('sensor_flow', 'Flow Sensor'), ('sensor_level', 'Level Sensor'), ('sensor_weight', 'Weight Sensor'), ('sensor_humidity', 'Humidity Sensor'), ('sensor_environmental', 'Environmental Sensor'), ('pump', 'Pump / VFD'), ('indicator', 'Indicator'), ('communication', 'Communication'), ('meter', 'Meter Under Test')], max_length=30)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='controller.devicegroup')),
            ],
            options={
                'ordering': ['display_order', 'device_id'],
            },
        ),
    ]
