# Generated by Django 5.0 on 2026-02-13 16:29

from django.db import migrations


def seed_devices(apps, schema_editor):
    DeviceGroup = apps.get_model('controller', 'DeviceGroup')
    FieldDevice = apps.get_model('controller', 'FieldDevice')

    # Groups
    groups = {}
    group_data = [
        ('Main Line', 'Primary flow path: supply → DUT', '#4CAF50', 1),
        ('Return Line', 'Return path: DUT → collection', '#2196F3', 2),
        ('Bypass', 'Bypass line', '#FF9800', 3),
        ('Pump & Drive', 'Pump and VFD', '#9C27B0', 4),
        ('Environment', 'Ambient and reservoir sensors', '#00BCD4', 5),
        ('Indicators', 'Tower light and visual indicators', '#F44336', 6),
        ('Communications', 'LoRa, Modbus buses', '#607D8B', 7),
    ]
    for name, desc, color, order in group_data:
        g = DeviceGroup.objects.create(
            name=name, description=desc, color=color, display_order=order,
        )
        groups[name] = g

    # Devices: (device_id, name, category, group, unit, min, max, order)
    devices = [
        # Main Line
        ('BV1', 'Ball Valve 1 — Inlet', 'valve', 'Main Line', '', None, None, 1),
        ('PT-01', 'Pressure Transmitter — Upstream', 'sensor_pressure', 'Main Line', 'bar', 0, 10, 2),
        ('FT-01', 'Reference Flow Meter', 'sensor_flow', 'Main Line', 'L/h', 0, 2500, 3),
        ('TT-01', 'Temperature Sensor — Inline', 'sensor_temperature', 'Main Line', '°C', 0, 50, 4),
        ('DUT', 'Meter Under Test', 'meter', 'Main Line', '', None, None, 5),
        # Return Line
        ('BV3', 'Ball Valve 3 — Outlet', 'valve', 'Return Line', '', None, None, 1),
        ('PT-02', 'Pressure Transmitter — Downstream', 'sensor_pressure', 'Return Line', 'bar', 0, 10, 2),
        ('WT-01', 'Weighing Scale', 'sensor_weight', 'Return Line', 'kg', 0, 200, 3),
        ('DV1', 'Diverter Valve', 'valve', 'Return Line', '', None, None, 4),
        ('DRN', 'Drain Valve', 'valve', 'Return Line', '', None, None, 5),
        # Bypass
        ('BV2', 'Ball Valve 2 — Bypass', 'valve', 'Bypass', '', None, None, 1),
        # Pump & Drive
        ('P-01', 'Multistage Vertical Pump', 'pump', 'Pump & Drive', 'Hz', 0, 50, 1),
        # Environment
        ('RES-LVL', 'Reservoir Level', 'sensor_level', 'Environment', '%', 0, 100, 1),
        ('RES-TEMP', 'Reservoir Water Temperature', 'sensor_temperature', 'Environment', '°C', 0, 50, 2),
        ('ATM-TEMP', 'Atmospheric Temperature', 'sensor_environmental', 'Environment', '°C', -10, 60, 3),
        ('ATM-HUM', 'Humidity', 'sensor_humidity', 'Environment', '%', 0, 100, 4),
        ('ATM-BARO', 'Barometric Pressure', 'sensor_environmental', 'Environment', 'hPa', 900, 1100, 5),
        # Indicators
        ('TOWER', 'Tower Light', 'indicator', 'Indicators', '', None, None, 1),
        # Communications
        ('LORA', 'LoRa Link (SX1262)', 'communication', 'Communications', '', None, None, 1),
        ('BUS1', 'Modbus Bus 1 — Sensors', 'communication', 'Communications', '', None, None, 2),
        ('BUS2', 'Modbus Bus 2 — VFD', 'communication', 'Communications', '', None, None, 3),
    ]
    for dev_id, name, cat, grp_name, unit, mn, mx, order in devices:
        FieldDevice.objects.create(
            device_id=dev_id, name=name, category=cat,
            group=groups[grp_name], unit=unit,
            min_value=mn, max_value=mx,
            display_order=order,
        )


def unseed(apps, schema_editor):
    apps.get_model('controller', 'FieldDevice').objects.all().delete()
    apps.get_model('controller', 'DeviceGroup').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_devices, unseed),
    ]
